---
abstract: 'Simple wrapper for Apple Push Notifications Service (APNS) provider'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-APNS
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0
  AnyEvent: 4.80
  JSON::Any: 0
  Net::SSLeay: 1.33
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/typester/anyevent-apns-perl.git
version: 0.05
